AWSTemplateFormatVersion: 2010-09-09
Description: >-
  SCI Template to create VPC on the basis of parameter input
Parameters:
    ClientName:
     Description: >- 
        Enter 3 character client code in lower case 
     Type: String
    CIDRBlock:
     Description: >-
      Enter the CIDR Block for VPC. For ex: 10.10.0.0/16
     Type: String
    NonProdAZ:
     Description: >-
        Select two availability zones that you want to use for non-production environments
     Type: "List<AWS::EC2::AvailabilityZone::Name>"
    ProdAZ:
     Description: >-
        Select two availability zones that you want to use for production environments.
     Type: "List<AWS::EC2::AvailabilityZone::Name>"
        
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      Tags:
        - Key: Name
          Value: !Join [ "_",[ !Ref ClientName, vpc ] ] 
        - Key: client
          Value: !Ref ClientName
        - Key: type
          Value: prod          
      CidrBlock: !Ref CIDRBlock
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'


  ProdSubnetPublic1:
    Type: 'AWS::EC2::Subnet'  
    Properties:
      MapPublicIpOnLaunch: 'false'
      AvailabilityZone: !Select 
        - '0'
        - !Ref ProdAZ
      VpcId: !Ref VPC
      CidrBlock: !Join [ ".",[!Select [0, !Split [".", !Ref CIDRBlock]],!Select [1, !Split [".", !Ref CIDRBlock]],2,0/24 ] ]
      Tags:
        - Key: Name
          Value: !Join [ "_",[ !Ref ClientName,prod,public,!Select [2, !Split ["-", !Select [0, !Ref ProdAZ]]] ]]
        - Key: client
          Value: !Ref ClientName
        - Key: type
          Value: prod
        - Key: usage
          Value: primary
  ProdSubnetPrivate1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      MapPublicIpOnLaunch: 'false'
      AvailabilityZone: !Select 
        - '0'
        - !Ref ProdAZ
      VpcId: !Ref VPC
      CidrBlock: !Join [ ".",[!Select [0, !Split [".", !Ref CIDRBlock]],!Select [1, !Split [".", !Ref CIDRBlock]],3,0/24 ] ]
      Tags:
        - Key: Name
          Value: !Join [ "_",[ !Ref ClientName,prod,private,!Select [2, !Split ["-", !Select [0, !Ref ProdAZ]]] ]]
        - Key: client
          Value: !Ref ClientName
        - Key: type
          Value: prod
        - Key: usage
          Value: primary
  ProdSubnetPublic2:
    Type: 'AWS::EC2::Subnet'  
    Properties:
      MapPublicIpOnLaunch: 'false'
      AvailabilityZone: !Select 
        - '1'
        - !Ref ProdAZ
      VpcId: !Ref VPC
      CidrBlock: !Join [ ".",[!Select [0, !Split [".", !Ref CIDRBlock]],!Select [1, !Split [".", !Ref CIDRBlock]],5,0/24 ] ]
      Tags:
        - Key: Name
          Value: !Join [ "_",[ !Ref ClientName,prod,public,!Select [2, !Split ["-", !Select [1, !Ref ProdAZ]]] ]]
        - Key: client
          Value: !Ref ClientName
        - Key: type
          Value: prod
        - Key: usage
          Value: secondary
  ProdSubnetPrivate2:
    Type: 'AWS::EC2::Subnet'
    Properties:
      MapPublicIpOnLaunch: 'false'
      AvailabilityZone: !Select 
        - '1'
        - !Ref ProdAZ
      VpcId: !Ref VPC
      CidrBlock: !Join [ ".",[!Select [0, !Split [".", !Ref CIDRBlock]],!Select [1, !Split [".", !Ref CIDRBlock]],6,0/24 ] ]
      Tags:
        - Key: Name
          Value: !Join [ "_",[ !Ref ClientName,prod,private,!Select [2, !Split ["-", !Select [1, !Ref ProdAZ]]] ]]
        - Key: client
          Value: !Ref ClientName
        - Key: type
          Value: prod
        - Key: usage
          Value: secondary
  
